# Représentation des entiers, un peu de Python...

Lors de la conception d'un programme les objects du monde réel (abstraits ou concrets) doivent être représentés sous une forme numérique. Cette capacité de modélisation est l'une des difficultés principales pour l'apprenti programmeur qu'il soit débutant ou non. Pire, pour les débutants, cet aspect est souvent négligé au profit de l'algorithmique et finalement une partie des élèves ne parviennent pas même à concevoir les algorithmes répondant à un problème posé dans un énoncé en français faute d'être capables d'imaginer quels objets numériques pourraient représenter le problème à résoudre. Les méthodes d'analyse permettent de répondre à cette difficulté mais, in fine, il faudra bien faire rentrer le modèle dans des représentations numériques de base telles que les chaînes de caractères, les nombres entiers, les nombres décimaux... 
Cette séquence de travail vous donnera des éléments permettant de manipuler des concepts python et de les illustrer sur le sujet de la représentation des nombres entiers.  



## 1. Conversion du décimal au binaire
### Entiers
Observer le fonctionnement des fonctions suivantes.

```python
a=42
b=1200
print(a)
print("{}".format(a))
print("{}".format(b))
```

In [48]:
a=42
b=1200
print(a)
print("{}".format(a))
print("{}".format(b))

42
42
1200


Il est possible de changer le format d'affichage. Expliquez les sorties suivantes:

```python
print("{:b}".format(a))
print("{:b}".format(b))
```

In [49]:
print("{:b}".format(a))
print("{:b}".format(b))

101010
10010110000


Si la base deux joue un rôle prépondérant en informatique, l'autre base également
utilisée de façon fréquente est la base 16, dite hexadécimale. Elle permet de décrire ou
de manipuler commodément une longue suite de bits. Il serait en effet vite difficile de manipuler des grandes séquences de bits, pour par exemple explorer un fichier ou entrer un code WIFI. On multiplierait ainsi les risques d'erreurs. Le cerveau humain est plus accoutumé à un faible nombre de symboles puisés parmi un grand choix plutôt qu'à une immense suite de symboles même s'ils sont puisés dans un ensemble de faible étendue.

Expliquez ceci:
```python
print("{:x}".format(a))
print("{:x}".format(b))
```

In [50]:
print("{:x}".format(a))
print("{:x}".format(b))

2a
4b0


On peut aussi faire l'inverse:
```python
  a=int("101010",2)
  print(a)
```

Testez avec `b`et avec d'autres bases...

In [75]:
a=int("101010",2)
print(a)
print("{}".format(a))
b=int("4b0",16)
print(b)
print("{}".format(b))


42
42
1200
1200


Il est même possible de formater la sortie en imposant un format précis:

```Python
print("{0:{fill}8b}".format(a, fill='0'))
```

In [3]:
print("{0:{fill}8b}".format(a, fill='0'))

00101010


Que se passe-t-il si on souhaite afficher un négatif?

In [4]:
print("{0:{fill}8b}".format(-a, fill='0'))

-0101010


Il serait naturel de représenter les entiers relatifs en utilisant un bit pour le signe et les autres pour la valeur absolue. Ainsi, avec des mots de 16 bits, on utiliserait 1 bit pour le signe et 15 bits pour la valeur absolue. Mais, outre l'existence de deux zéros, cela ne facilite pas du tout les traitements arithmétiques. 

La plupart des langages appliquent une autre méthode, qui consiste à représenter un entier relatif par
un entier naturel. Si on utilise des mots de 16 bits, on peut représenter les **entiers relatifs** compris entre -32 768 et 32767. Donc sur 16 bits, on représente un entier relatif z **positif ou nul**
comme l'entier naturel x et un entier relatif r **strictement négatif** comme l'entier naturel
$x + 2^{16} = x + 65 536$, qui est compris entre 32 768 et 65 535. Ainsi, les entiers naturels
de 0 à 32 767 correspondent aux entiers relatifs positifs ou nuls, à droite sur la figure ci-dessous et
les entiers naturels de 32 768 à 65 535 représentent les entiers relatifs strictement négatifs
à gauche sur cette même figure.


<img src="fig/cerclemodulo.png" alt="cercleModulo.png"
	title="cercleModulo.png" width="200"  />


Finalement on peut résumer la situation ainsi: dans certains intervalles fixés par les limites imposées par le nombre de bits disponibles noté $Nb$, les entiers relatifs sont représentés par leur valeur modulo $2^{Nb}$.

Explorons ce mode de repésentation dénommé **C2**.

Lorsque l'on s'intéresse au C2, il faut d'abord s'entendre sur le nombre de bits sur lequel on travaille. Certains processeurs (plutôt anciens) travaillent sur des représentations sur 8 bits. Dans ce cas les entiers relatifs vont de $-2^{8}$ à $2^{7}-1$. 

Utilisez les formats d'affichage en Python afin de représenter a=42 et b=-42 sur 8 bits en **C2** 


In [13]:
print("{0:{fill}8b}".format(a%256, fill='0'))
b=-a
print("{0:{fill}8b}".format(b%256, fill='0'))

00101010
11010110


Effectuez l'opération $c=b+1$ et affichez en **C2**.

In [53]:
c=b+1
print("{0:{fill}8b}".format(c%256, fill='0'))

10110001


Affichez l'opposé de c:   $d=-c $ et affichez en **C2**.

In [55]:
d=-c
print("{0:{fill}8b}".format(d%256, fill='0'))

01001111


Affichez l'addition de $e=d+b$  et affichez en **C2**. Comment interpréter ce résultat?

In [56]:
e=d+b
print("{0:{fill}8b}".format(e%256, fill='0'))

11111111


Passage à 32 bits. Refaites les mêmes calculs et affichages mais cette fois-ci sur 32 bits.
Affichez les limites de représentations sur 32bits.
Nota: en Python l'exposant est dénoté: `**` par exemple $x^2$ est codé ainsi: `x**2`

In [31]:
largeur=32
print("{0:{fill}32b}".format(a%(2**largeur), fill='0'))
b=-a
print("{0:{fill}32b}".format(b%(2**largeur), fill='0'))
c=b+1
print("{0:{fill}32b}".format(c%(2**largeur), fill='0'))
d=-c
print("{0:{fill}32b}".format(d%(2**largeur), fill='0'))
min=-2**(largeur-1)
max=2**(largeur-1)-1
print("min:  ",min,"max:  ",max)

00000000000000000000000000101010
11111111111111111111111111010110
11111111111111111111111111010111
00000000000000000000000000101001
min:   -2147483648 max:   2147483647


Passage à 64 bits. Refaites la même chose cette fois-ci en format double précision (64bits)

In [9]:
largeur=64
print("{0:{fill}64b}".format(a%(2**largeur), fill='0'))
b=-a
print("{0:{fill}64b}".format(b%(2**largeur), fill='0'))
c=b+1
print("{0:{fill}64b}".format(c%(2**largeur), fill='0'))
d=-c
print("{0:{fill}64b}".format(d%(2**largeur), fill='0'))
min=-2**(largeur-1)
max=2**(largeur-1)-1
print("min:  ",min,"max:  ",max)

0000000000000000000000000000000000000000000000000000000000101010
1111111111111111111111111111111111111111111111111111111111010110
1111111111111111111111111111111111111111111111111111111111010111
0000000000000000000000000000000000000000000000000000000000101001
min:   -9223372036854775808 max:   9223372036854775807


Comment inverser la conversion? Vous devez partir d'une chaine repésentant un nombre codé en **C2** sur par exemple 8 bits: "11010111" ou encore  "00101010" 

Comment savoir si c'est un positif ou un négatif? 

Complétez ce code afin d'obtenir cet affichage à partir des mêmes chaînes en entrée.
```Python
print(int("11010111",2))
print(int("00101010",2))
....
```

Affichage: 
```
215
42
-41
42
```

In [17]:

print(int("11010111",2))
print(int("00101010",2))

str="11010111"
print(int(str,2)-(256 if str[0]=="1" else 0))
str="00101010"
print(int(str,2)-(256 if str[0]=="1" else 0))

215
42
-41
42


Passage à 64 bits:
Complétez ce code afin d'obtenir cet affichage à partir des mêmes chaînes en entrée.
```Python
largeur=64

str1="0000000000000000000000000000000000000000000000000000000000101010"
str2="1111111111111111111111111111111111111111111111111111111111010110"

print(int(str1,2))
print(int(str2,2))
....
```

Affichage: 
```
215
42
-41
42
```

In [2]:
largeur=64

str1="0000000000000000000000000000000000000000000000000000000000101010"
str2="1111111111111111111111111111111111111111111111111111111111010110"
print(int(str1,2))
print(int(str2,2))



print(int(str1,2)-(2**largeur if str1[0]=="1" else 0))

print(int(str2,2)-(2**largeur if str2[0]=="1" else 0))

42
18446744073709551574
42
-42


Il est possible d'utiliser les types du langage C grâce à la librarie `ctypes`.

In [42]:
import ctypes

x=ctypes.c_int(42)
print(x)

c_int(42)


Il est possible de regarder la structure interne de l'entier en **C2** . Expliquez les sorties ci-après.

Nota:

Pour accéder à la représentation en mémoire d'un entier, on le met sous la forme d'une séquence de bytes. La fonction "pack" du module struct (https://docs.python.org/3/library/struct.html) permet d'effectuer cette transformation, on note en particulier l'usage de "!" pour fixer une représentation gros-boutiste. La fonction unpack fait la transformation inverse.

La chaîne de caractères produite est préfixée par "b" et est la suite des codes ascii (ou de leur interprétation si elle est affichable) représentant les codes hexadécimaux des octets.

<img src="fig/1280px-USASCII_code_chart.png" alt="1280px-USASCII_code_chart.png"
	title="1280px-USASCII_code_chart.png" width="400"  />

In [29]:
import struct 
import binascii

out = struct.pack('!i', 42)
print(out)
print(binascii.hexlify(out))
out = struct.pack('!i', -42)
print(out)
print(binascii.hexlify(out))

b'\x00\x00\x00*'
b'0000002a'
b'\xff\xff\xff\xd6'
b'ffffffd6'


Mais il est possible d'interpréter différement une même séquence de bits, soit sous hypothèse que c'est un entier, soit sous hypothèse que c'est un entier signé. Pour plus d'informations voir: https://docs.python.org/2/library/struct.html  et : https://bip.weizmann.ac.il/course/python/PyMOTW/PyMOTW/docs/struct/index.html

In [47]:
z=42
out = struct.pack('!I', z)
print(binascii.hexlify(out))
i=struct.unpack('!I',out)

print(z," donne: ",i[0])

z=-42
out = struct.pack('!i', z)
print(binascii.hexlify(out))
i=struct.unpack('!I',out)
print(z," donne: ",i[0])

b'0000002a'
42  donne:  42
b'ffffffd6'
-42  donne:  4294967254


### Algos de conversions .... 
Vous trouverez ici des exemple d'exercices à demander aux élèves. Ce sont des exemples de base en algorithmique et ils portent sur le thème du codage.

#### Représenter en base $k$ un entier naturel donné en base $10$

Pour écrire les entiers naturels en base $k$, on a besoin de $k$ chiffres. Quand on a
$r$ objets, on les groupe par paquets de $k$, puis on groupe ces paquets en paquets de
paquets, etc. Autrement dit, on fait une succession de divisions par $k$, jusqu'à obtenir un quotient égal à 0. 


Plus formellement, si l'on note $a_i,a_{i-1},...,a_1,a_0$ l'écriture de $n$ en base $k$, elle est obtenue
pour l'algorithme suivant:

entrées: $n,k$

$i\leftarrow 0$

tant que $n \neq 0$ faire

+ $a_i \leftarrow$ reste de la division euclidienne de $n$ par $k$
+ $n \leftarrow$ quotient de la division euclidienne de $n$ par $k$
+ $i\leftarrow i+1$
  
résultat: $a_i,a_{i-1},...,a_1,a_0$



In [60]:
def inttostring(n,b,digits="0123456789ABCDEF"):
    """Retourne la chaîne de caractères représentant n en base b, en utilisant les caractères de digits."""
    s=""
    while n != 0:
        s = digits[n%b] + s
        n=n//b
    s=digits[n] + s
    return s

print(inttostring(10,2))

01010


Pour trouver la représentation en base dix d'un entier naturel donné en base $k$, on
utilise le fait qu'en base $k$, le chiffre le plus à droite représente les unités, le précédent
les paquets de $k$, le précédent les paquets de $k \times k=k^2$, le précédent les paquets de
$k \times  k \times  k = k^3$, etc.
On retrouve les opérations réciproques de celles effectuées dans l'algorithme de
conversion en base $k$. 

Si $a_i,a_{i-1},...,a_1,a_0$ est l'écriture de $n$ en base $k$, alors:

$n=a_0+a_{1}k+a_2k^2+...+a_ik^i$ 

Ce calcul suppose  $(i+1) + i + … + 1 = (i+1)(i+2)/2 $ produits: $O(n^2)$.


La fonction "int" ne permet pas de dépasser la base 36. Écrire une fonction prenant en paramètres une chaîne de caractères s et une base k inférieure à 64 et retournant l'entier dont l'écriture en base k est s.

Codez cet algo de deux façons: dans un cas le parcours est effectué dans l'ordre de la chaîne et dans l'autre le parcours est effectué dans l'ordre inverse. 

Aide: 
Pour avoir le rang du caractère c dans digits vous pouvez utiliser:
```Python
digits.index(c)
```

In [65]:
def stringtoint(s,k,digits="0123456789ABCDEF"):
    """Retourne l'entier représenté par la chaîne de caractères s en base k."""
    n=0
    exp=0
    for c in s[::-1]:
        if digits.index(c)<k:
            n += (k**exp)*digits.index(c)
            exp+=1
        else:
            raise Exception("Erreur lors de la lecture de la châine représentant le nombre")
                 
                
    return n

print(stringtoint('4A', 16,digits="0123456789ABCDEF"))

A
4
74


In [69]:
def stringtoint(s,k,digits="0123456789ABCDEF"):
    """Retourne l'entier représenté par la chaîne de caractères s en base k."""
    n=0
    exp=1
    taille=len(s)
    for c in s:
        if digits.index(c)<k:
            n += (k**(taille-exp))*digits.index(c)
            exp+=1
        else:
            raise Exception("Erreur lors de la lecture de la châine représentant le nombre")
                 
                
    return n

print(stringtoint('4A', 16,digits="0123456789ABCDEF"))

74



 
 Si $a_i,a_{i-1},...,a_1,a_0$ est l'écriture de $n$ en base $k$, alors
on peut également suivre la méthode de Horner (vous l'avez par exemple fait étudier à vos élèves en cours de mathématiques)
pour faire ce calcul plus efficacement. Ce calcul suppose  $i $ produits: $O(n)$. Cela permet aussi plus naturellement de faire
le calcul en lisant les chiffres de gauche à droite.

$n=((( ... (a_ik+a_{i-1})k+...)k+a_2)k+a_{1})k+a_0$

In [75]:
def stringtoint(s,k,digits="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"):
    """Retourne l'entier représenté par la chaîne de caractères s en base k."""
    n=0
    for c in s:
        if digits.index(c)<k:
            n = k*n + digits.index(c)
        else:
            raise Exception("Erreur lors de la lecture de la châine représentant le nombre")
                 
                
    return n

print(stringtoint('AQ', 35,digits="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"))
    

376


### Mais les entiers python sont sophistiqués...
Sont-ils codés sur 32 bits comme les entiers signés en  Java ou en C++? Sont-ils codés sur 64 bits comme les `double` en Java ou en C++? Pour en avoir confirmation, essayez d'afficher le maximum +1 sur 32 bits, sur 64bits? 

In [3]:
min=-2**(largeur-1)+1
max=2**(largeur-1)-1-1
print("min:  ",min,"max:  ",max)

min:   -9223372036854775807 max:   9223372036854775806


Peut-être sont-ils codés sur 128 bits? Essayez...

In [4]:
largeur=128
min=-2**(largeur-1)
max=2**(largeur-1)-1
print("min:  ",min,"max:  ",max)

min:   -170141183460469231731687303715884105728 max:   170141183460469231731687303715884105727


Affichez les valeurs maximums en négatif comme en positif en faisant varier le nombre de bits utilisé de 2 à 4096. Où trouvez-vous la limite?

Exemple d'affichage: 
```Python
print("exposant:  ",largeur ,"\nmin:  ",min,"\nmax:  ",max)
```

In [5]:
for i in range(1,13):
    largeur=2**i
    min=-2**(largeur-1)
    max=2**(largeur-1)-1
    print("exposant:  ",largeur ,"\nmin:  ",min,"\nmax:  ",max)

exposant:   2 
min:   -2 
max:   1
exposant:   4 
min:   -8 
max:   7
exposant:   8 
min:   -128 
max:   127
exposant:   16 
min:   -32768 
max:   32767
exposant:   32 
min:   -2147483648 
max:   2147483647
exposant:   64 
min:   -9223372036854775808 
max:   9223372036854775807
exposant:   128 
min:   -170141183460469231731687303715884105728 
max:   170141183460469231731687303715884105727
exposant:   256 
min:   -57896044618658097711785492504343953926634992332820282019728792003956564819968 
max:   57896044618658097711785492504343953926634992332820282019728792003956564819967
exposant:   512 
min:   -6703903964971298549787012499102923063739682910296196688861780721860882015036773488400937149083451713845015929093243025426876941405973284973216824503042048 
max:   6703903964971298549787012499102923063739682910296196688861780721860882015036773488400937149083451713845015929093243025426876941405973284973216824503042047
exposant:   1024 
min:   -89884656743115795386465259539451236680898848947115

La librairie ```sys``` permet de savoir la taille en octets de la repésentation de l'entier
```Python
import sys
largeur=40
a=2**(largeur-1)-1
print(sys.getsizeof(a))
```

In [6]:
import sys
largeur=40
a=2**(largeur-1)-1
print(sys.getsizeof(a))

32


Quel est le minimum? Incrémentez dans une boucle jusqu'à: 2**2048?

In [50]:
import sys
for i in range(1,13):
    largeur=2**i
    min=-2**(largeur-1)
    max=2**(largeur-1)-1
    print("exposant:  ",largeur ,"\nmin:  ",sys.getsizeof(min),"\nmax:  ",sys.getsizeof(max))

exposant:   2 
min:   28 
max:   28
exposant:   4 
min:   28 
max:   28
exposant:   8 
min:   28 
max:   28
exposant:   16 
min:   28 
max:   28
exposant:   32 
min:   32 
max:   32
exposant:   64 
min:   36 
max:   36
exposant:   128 
min:   44 
max:   44
exposant:   256 
min:   60 
max:   60
exposant:   512 
min:   96 
max:   96
exposant:   1024 
min:   164 
max:   164
exposant:   2048 
min:   300 
max:   300
exposant:   4096 
min:   572 
max:   572


La taille semble évoluer en fonction des besoins...
Pour mieux comprendre on peut utiliser la classe: `PyLongObject` de `ctype`

La librairie `ctype` permet d'accéder aux structures de données écrites en C qui sont utilisées par l'interpréteur python c'est-à-dire le logiciel qui exécute le code python. On dit qu'il l'interprète.  Par conséquent il est possible grâce à cette librairie d'explorer comme sont repésentés les entiers en Python.

Il est ainsi possible d'afficher par exemple une partie des données contenues dans la structure de données `PyLongObject`, laquelle permet de représenter les entiers en Python. 

```python
import ctypes
class PyLongObject(ctypes.Structure):
        _fields_ = [("ob_refcnt", ctypes.c_long),
                ("ob_type", ctypes.c_void_p),
                ("ob_size", ctypes.c_ulong),
                ("ob_digit", ctypes.c_int *1)]

bignum = 2**40-1
the_int=PyLongObject.from_address(id(bignum)) # recupère l'objet via son identifiant 
size=the_int.ob_size # recupère la sous-partie ob_size (qui est un long entier non signé et donc codé sur 64 bit)
print( size)
    ```


In [49]:
import ctypes
class PyLongObject(ctypes.Structure):
        _fields_ = [("ob_refcnt", ctypes.c_long),
                ("ob_type", ctypes.c_void_p),
                ("ob_size", ctypes.c_ulong),
                ("ob_digit", ctypes.c_int *1)]

bignum = 2**40-1
the_int=PyLongObject.from_address(id(bignum)) # recupère l'objet via son identifiant 
size=the_int.ob_size # recupère la sous-partie ob_size (qui est un long entier non signé et donc codé sur 64 bit)
print( size)

2


Il semble donc que les entiers stockent une taille mais laquelle? A quoi correspond-elle?
Pour le savoir allons explorer la dernière partie de la structure de données `PyLongObject` c'est-à-dire `ob_digit`
```Python
import ctypes
class PyLongObject(ctypes.Structure):
        _fields_ = [("ob_refcnt", ctypes.c_long),
                ("ob_type", ctypes.c_void_p),
                ("ob_size", ctypes.c_ulong),
                ("ob_digit", ctypes.c_int *1)]
        
bignum = 2**40-1
the_int=PyLongObject.from_address(id(bignum))
size=the_int.ob_size
print( size)

x=the_int.ob_digit  # récupère ob_digit qui est l'adresse d'un tableau d'entiers C  (c_int *)
px= ctypes.cast(ctypes.pointer(x),ctypes.POINTER(ctypes.c_int))# transforme le tableau d'entiers C en tableau Python
print(px[0]) #Affiche la première case du tableau python.
```


In [7]:
import ctypes
class PyLongObject(ctypes.Structure):
        _fields_ = [("ob_refcnt", ctypes.c_long),
                ("ob_type", ctypes.c_void_p),
                ("ob_size", ctypes.c_ulong),
                ("ob_digit", ctypes.c_int *1)]
        
bignum = 2**40-1
the_int=PyLongObject.from_address(id(bignum))
size=the_int.ob_size
print( size)

x=the_int.ob_digit  # récupère ob_digit qui est l'adresse d'un tableau d'entiers C  (c_int *)
px= ctypes.cast(ctypes.pointer(x),ctypes.POINTER(ctypes.c_int))#transforme le tableau d'entiers C en tableau Python
print(px[0]) #Affiche la première case du tableau python.

2
1073741823


Explorez un peu plus loin ce tableau... Par exemple de 2 cases. 

NB: il serait possible d'explorer bien plus loin car le code tel qu'il est conçu ici ne tient pas compte de la taille réelle du tableau. Par conséquent les valeurs au delà de 2 cases ne sont pas facilement interprétables.

In [65]:
import ctypes
class PyLongObject(ctypes.Structure):
        _fields_ = [("ob_refcnt", ctypes.c_long),
                ("ob_type", ctypes.c_void_p),
                ("ob_size", ctypes.c_ulong),
                ("ob_digit", ctypes.c_int *1)]
        
bignum = 2**40-1
the_int=PyLongObject.from_address(id(bignum))
size=the_int.ob_size
print( size)

x=the_int.ob_digit  # récupère ob_digit qui est l'adresse d'un tableau d'entiers C  (c_int *)
px= ctypes.cast(ctypes.pointer(x),ctypes.POINTER(ctypes.c_int))# transforme  le tableau d'entiers C en tableau Python
print(px[0]) #Affiche la première case du tableau python.
print(px[1]) 
 

2
1073741823
1023


Afficher sur 64 bits la représentation en binaire C2 de  `2**40-1`puis de `1073741823`, puis de `1023`. Que remarque-t-on? Quelles hypothèses peut-on faire sur la représentation des entiers en python? 

In [67]:
print("{0:{fill}64b}".format((2**40-1)%(2**64), fill='0'))

print("{0:{fill}64b}".format(1073741823%(2**64), fill='0'))
print("{0:{fill}64b}".format(1023%(2**64), fill='0'))


0000000000000000000000001111111111111111111111111111111111111111
0000000000000000000000000000000000111111111111111111111111111111
0000000000000000000000000000000000000000000000000000001111111111


Affichez les `size` cases du tableau ob_digit. 

In [68]:
import ctypes
class PyLongObject(ctypes.Structure):
        _fields_ = [("ob_refcnt", ctypes.c_long),
                ("ob_type", ctypes.c_void_p),
                ("ob_size", ctypes.c_ulong),
                ("ob_digit", ctypes.c_int *1)]
        
bignum = 2**40-1
the_int=PyLongObject.from_address(id(bignum))
size=the_int.ob_size
print( size)

x=the_int.ob_digit
px= ctypes.cast(ctypes.pointer(x),ctypes.POINTER(ctypes.c_int))
for d in range(0,size):
    print(px[d])

2
1073741823
1023


Recommencez dans une boucle afin d'analyser comment les valeurs maximum évoluent dans les exemples plus hauts qui parcourent les exposants de 2 à 2048:
```Python
for i in range(1,13):
    largeur=2**i
    max=2**(largeur-1)-1
    ........
 ```   

In [77]:
import sys
import ctypes

for i in range(1,13):
    largeur=2**i
    max=2**(largeur-1)-1
    print("exposant:  ",largeur ,"\n max:  ",max,"\n size max:  ",sys.getsizeof(max))
    
    
    the_int=PyLongObject.from_address(id(max))
    size=the_int.ob_size
    print( size)

    x=the_int.ob_digit
    px= ctypes.cast(ctypes.pointer(x),ctypes.POINTER(ctypes.c_int))
    for d in range(0,size):
        print(px[d])

exposant:   2 
 max:   1 
 size max:   28
1
1
exposant:   4 
 max:   7 
 size max:   28
1
7
exposant:   8 
 max:   127 
 size max:   28
1
127
exposant:   16 
 max:   32767 
 size max:   28
1
32767
exposant:   32 
 max:   2147483647 
 size max:   32
2
1073741823
1
exposant:   64 
 max:   9223372036854775807 
 size max:   36
3
1073741823
1073741823
7
exposant:   128 
 max:   170141183460469231731687303715884105727 
 size max:   44
5
1073741823
1073741823
1073741823
1073741823
127
exposant:   256 
 max:   57896044618658097711785492504343953926634992332820282019728792003956564819967 
 size max:   60
9
1073741823
1073741823
1073741823
1073741823
1073741823
1073741823
1073741823
1073741823
32767
exposant:   512 
 max:   6703903964971298549787012499102923063739682910296196688861780721860882015036773488400937149083451713845015929093243025426876941405973284973216824503042047 
 size max:   96
18
1073741823
1073741823
1073741823
1073741823
1073741823
1073741823
1073741823
1073741823
1073741823
10

Il semble que le format de sauvegarde des entiers décompose l'entier en morceaux. De quelle taille? vous pouvez répondre en utilisant le log à base 2 de python:
```Python
import math
print(math.log(8,2))
print(math.log(1073741823,2))
```


In [54]:
import math
print(math.log(8,2))
print(math.log(1073741823,2))


3.0
29.999999998656385


A présent vous savez comment sont repésentés les nombre entiers en python et vous pouvez manipuler le tableau qui stoke les chiffres qui le compose. Exercice: recomposez le nombre à partir de ses morceaux:

In [79]:
import sys
import ctypes

for i in range(1,10):
    largeur=2**i
    max=2**(largeur-1)-1
    print("exposant:  ",largeur ,"\n max:  ",max,"\n size max:  ",sys.getsizeof(max))
    
    size=PyLongObject.from_address(id(max)).ob_size
    x=PyLongObject.from_address(id(max)).ob_digit
    px= ctypes.cast(ctypes.pointer(x),ctypes.POINTER(ctypes.c_int))
    
    print(size)
    acc=0
    i=0
    for d in range(0,size):
        val=px[d]
        print(val)
        acc=acc+val*2**(30*(i))
        i=i+1
    print("recomposé:  ",acc)   
    
    

exposant:   2 
 max:   1 
 size max:   28
1
1
recomposé:   1
exposant:   4 
 max:   7 
 size max:   28
1
7
recomposé:   7
exposant:   8 
 max:   127 
 size max:   28
1
127
recomposé:   127
exposant:   16 
 max:   32767 
 size max:   28
1
32767
recomposé:   32767
exposant:   32 
 max:   2147483647 
 size max:   32
2
1073741823
1
recomposé:   2147483647
exposant:   64 
 max:   9223372036854775807 
 size max:   36
3
1073741823
1073741823
7
recomposé:   9223372036854775807
exposant:   128 
 max:   170141183460469231731687303715884105727 
 size max:   44
5
1073741823
1073741823
1073741823
1073741823
127
recomposé:   170141183460469231731687303715884105727
exposant:   256 
 max:   57896044618658097711785492504343953926634992332820282019728792003956564819967 
 size max:   60
9
1073741823
1073741823
1073741823
1073741823
1073741823
1073741823
1073741823
1073741823
32767
recomposé:   57896044618658097711785492504343953926634992332820282019728792003956564819967
exposant:   512 
 max:   670390396